CREATE DATABASE genesisresources;

CREATE TABLE genesisresources.register (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY UNIQUE NOT NULL,
    Name VARCHAR(255) NOT NULL,
    Surname VARCHAR(255),
    PersonID VARCHAR(12) UNIQUE NOT NULL,
    Uuid VARCHAR(36) UNIQUE NOT NULL
);